version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: hjiang
      POSTGRES_PASSWORD: jiang186212
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/dbata