version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: zytz2609
      RABBITMQ_DEFAULT_PASS: A88888888
    ports:
      - "25672:5672"   # RabbitMQ port
      - "15672:15672"  # RabbitMQ management console port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Data volume
      - rabbitmq_logs:/var/log/rabbitmq  # Log volume
volumes:
  rabbitmq_data:
  rabbitmq_logs:
